### ISSUE TITLE
Notification Failure

### ISSUE THREAD

**Issue by ro53ben** [LosCV29/ha-video-vision#1]
I seem unable to get this working, have installed, configured and set-up an automation triggered from the doorbell.

Getting the following in my HA core logs:

This error originated from a custom integration.

Logger: custom_components.ha_video_vision
Source: custom_components/ha_video_vision/__init__.py:924
integration: HA Video Vision (documentation, issues)
First occurred: 15:02:21 (2 occurrences)
Last logged: 15:08:58

Notification error for notify.mobile_app_ben12r: Action notify.ben12r not found

---

Not sure why it's trying to do action notify.ben12r, when I entered the full string in the config.

Any help appreciated, thanks.

**Comment by LosCV29** [comment]
> I seem unable to get this working, have installed, configured and set-up an automation triggered from the doorbell.
> 
> Getting the following in my HA core logs:
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.ha_video_vision Source: custom_components/ha_video_vision/**init**.py:924 integration: HA Video Vision (documentation, issues) First occurred: 15:02:21 (2 occurrences) Last logged: 15:08:58
> 
> Notification error for notify.mobile_app_ben12r: Action notify.ben12r not found
> 
> Not sure why it's trying to do action notify.ben12r, when I entered the full string in the config.
> 
> Any help appreciated, thanks.

good morning. Apologies your integration isnt working. I've released a new version that takes care of notifications through an included blueprint. Go ahead and install the latest version and use the included blueprint for notifications. Let me know if it works.

**Comment by ro53ben** [comment]
I upgraded yesterday, the blueprint is a better model, thanks.

I still have issues but I shall close this one as it's no longer relevant to the project.

Appreciate the work on this so far.

**Comment by ro53ben** [comment]
Notifications function was resigned
